# Use YAML for configuration since it allows comments like this
site_name: Agrogeo24
description: Agrogeo24
author: Agrogeophysics Organizing Committee
language: en
repository: agrogeophy/agrogeo24
favicon: images/logo2.jpg
logo: images/logo1.jpg
menu:
  - [Home, index]  
  - [Committee, committees]
#  - [About, about]
#  - [Agenda, program]
#  - [<font color="blue">Workshop</font>, workshop ]
  - [<font color="green">Submit an abstract</font>, abstracts]  
#  - [<font color="red">COVID-19 information</font>, COVID19]  
#  - [Gallery, gallery]
extra_navlinks:
  - [Program, https://agrogeo24.curve.space/]
ignore:
  - README.md
  - config-alternative.json
  - Makefile
keywords: 'agrogeophysics, hydrogeophysics, ERT, EMI, GPR, seismic, NMR, applied geophysics, remote sensing, open-source'
language: en

